language: java

dist: xenial

jdk:
    - openjdk11

before_install:
    - chmod +x mvnw

script:
    - ./mvnw -B -f rcp.demo.build/pom.xml -PDefault
    - ./mvnw -B -f rcp.demo.build/pom.tests.core.xml -PTest
